url: https://werreales.neocities.org

permalink: pretty

destination: OUT

defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  -
    scope:
      path: 'assets'
    values:
      layout: ~
