url: https://werreales.github.io
baseurl: /factbooks

permalink: pretty

defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  -
    scope:
      path: 'assets'
    values:
      layout: ~
